### ISSUE TITLE
Make sure attrs() are implemented on all possible types

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#124]
Currently, types which don't allocate heap memory can't have `attrs()`.

It's unclear how this could be implemented without memory/performance impact.

**Comment by ilyash** [comment]
Design Idea: transparent container for types like Int, Bool, etc. Whoever is interested can call a function and get the value wrapped in the container.

Use case: attrs() on parsed JSON, which can be anything.

**Comment by ilyash-b** [comment]
In `dev`
