### ISSUE TITLE
Consider implementing skip(Iter, Int)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#171]

**Comment by antonio-pedro99** [comment]
can you elaborate more on this?

**Comment by ilyash-b** [comment]
Skip (fetch and discard, using `next()`) given number of elements from the iterator. Should return same `Iter`ator.

**Comment by ilyash-b** [comment]
Implement the `Iter` file

Todo: test cases (@ilyash-b )

**Comment by ilyash-b** [comment]
PR merged. In `dev`.
