### ISSUE TITLE
Exceptions user friendliness

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#186]
Currently when throwing and exception with message the output shows:

ngs -pi 'throw Exception("hello")'
[ERROR 2018-10-04 10:17:29 CEST] --- Exception ---
[ERROR 2018-10-04 10:17:29 CEST] Exception of type Exception occurred
[ERROR 2018-10-04 10:17:29 CEST] Message: hello
[ERROR 2018-10-04 10:17:29 CEST] Frame 0: /usr/local/lib/ngs/bootstrap.ngs:294:1 - 294:34
[ERROR 2018-10-04 10:17:29 CEST] Frame 1: /usr/local/lib/ngs/bootstrap.ngs:267:20 - 267:29 [in bootstrap_exception_catch_wrapper]
[ERROR 2018-10-04 10:17:29 CEST] Frame 2: /usr/local/lib/ngs/bootstrap.ngs:201:11 - 201:23 [in bootstrap]
[ERROR 2018-10-04 10:17:29 CEST] Frame 3: <command line -pi switch>:2:7 - 2:16

Would be nice to see the message before the exception like: 

ngs -pi 'throw Exception("hello")'
[ERROR 2018-10-04 10:17:29 CEST] Message: hello
[ERROR 2018-10-04 10:17:29 CEST] 
[ERROR 2018-10-04 10:17:29 CEST] --- Exception ---
[ERROR 2018-10-04 10:17:29 CEST] Exception of type Exception occurred
[ERROR 2018-10-04 10:17:29 CEST] Frame 0: /usr/local/lib/ngs/bootstrap.ngs:294:1 - 294:34
[ERROR 2018-10-04 10:17:29 CEST] Frame 1: /usr/local/lib/ngs/bootstrap.ngs:267:20 - 267:29 [in bootstrap_exception_catch_wrapper]
[ERROR 2018-10-04 10:17:29 CEST] Frame 2: /usr/local/lib/ngs/bootstrap.ngs:201:11 - 201:23 [in bootstrap]
[ERROR 2018-10-04 10:17:29 CEST] Frame 3: <command line -pi switch>:2:7 - 2:16

**Comment by ilyash-b** [comment]
```
$ ngs -pi 'throw Exception("hello")'
[ERROR 2018-11-18 16:33:52 IST] +-------+
[ERROR 2018-11-18 16:33:52 IST] | hello |
[ERROR 2018-11-18 16:33:52 IST] +-------+
[ERROR 2018-11-18 16:33:52 IST] Exception of type Exception occurred
[ERROR 2018-11-18 16:33:52 IST] Frame 0: /usr/local/lib/ngs/bootstrap.ngs:290:1 - 290:34
[ERROR 2018-11-18 16:33:52 IST] Frame 1: /usr/local/lib/ngs/bootstrap.ngs:264:20 - 264:29 [in bootstrap_exception_catch_wrapper]
[ERROR 2018-11-18 16:33:52 IST] Frame 2: /usr/local/lib/ngs/bootstrap.ngs:201:11 - 201:23 [in bootstrap]
[ERROR 2018-11-18 16:33:52 IST] Frame 3: <command line -pi switch>:2:7 - 2:16
+-------+
| hello |
+-------+
```

**Comment by ilyash-b** [comment]
```
$ N 'decode_json("{a:1}")'
[ERROR 2018-11-18 16:40:48 IST] +-----------------------------------------------------+
[ERROR 2018-11-18 16:40:48 IST] | Failed to parse JSON                                |
[ERROR 2018-11-18 16:40:48 IST] | Error message: quoted object property name expected |
[ERROR 2018-11-18 16:40:48 IST] | Error position in given JSON: 1                     |
[ERROR 2018-11-18 16:40:48 IST] | (TODO: show relevant value part)                    |
[ERROR 2018-11-18 16:40:48 IST] +-----------------------------------------------------+
[ERROR 2018-11-18 16:40:48 IST] Exception of type JsonDecodeFail occurred
[ERROR 2018-11-18 16:40:48 IST] Info: error = String(36): quoted object property name expected
[ERROR 2018-11-18 16:40:48 IST] Info: value = String(5): {a:1}
[ERROR 2018-11-18 16:40:48 IST] Info: position = Int: 1
[ERROR 2018-11-18 16:40:48 IST] Frame 0: /usr/local/lib/ngs/bootstrap.ngs:290:1 - 290:34
[ERROR 2018-11-18 16:40:48 IST] Frame 1: /usr/local/lib/ngs/bootstrap.ngs:264:20 - 264:29 [in bootstrap_exception_catch_wrapper]
[ERROR 2018-11-18 16:40:48 IST] Frame 2: /usr/local/lib/ngs/bootstrap.ngs:201:11 - 201:23 [in bootstrap]
[ERROR 2018-11-18 16:40:48 IST] Frame 3: <command line -pi switch>:2:1 - 2:12
+-----------------------------------------------------+
| Failed to parse JSON                                |
| Error message: quoted object property name expected |
| Error position in given JSON: 1                     |
| (TODO: show relevant value part)                    |
+-----------------------------------------------------+
```

**Comment by ilyash-b** [comment]
In `dev`
