### ISSUE TITLE
Running NGS without parameters should give meaningful message

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#21]
While ngs doesn't have a cli, the normal ngs with no parameters should return some sort of help and not the errors and exception. This leads the user to think the ngs is not correctly installed.

**Comment by ilyash-b** [comment]
If you get to this first, modify `lib/cli.ngs` to change the behaviour. I suggest that current behaviour would be unlocked by setting the `NGS_CLI_DEV` environment variable. If the variable is not set, let the user know that the shell is not ready yet.

**Comment by ilyash-b** [comment]
In dev
