### ISSUE TITLE
Integrate libcurl

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#216]
From todo.txt:

+ Make libcurl optional with compile time switch. If curl is compiled, add "curl": CURL_VERSION pair to FEATURES.
+ Use namespace "curl"
+ Low level functions in the namespace will be called "c_..." as all other low level c functions that are exposed to NGS language.
+ Higher level functions and types also go into the "curl" namespace, these will be the interface used by the rest of NGS code.
+ Integration: when read() sees a URL that starts with a scheme that libcurl supports, use libcurl to obtain the resource. Think about passing credentials, etc.
+ Think about stream processing for large resources, where read() will not be appropriate
+ Think about write() integration. Should it "POST"?

**Comment by ilyash** [comment]
Not enough real life use cases
