### ISSUE TITLE
Implement assert_proc(cp:CommandsPipeline, exit_code, stdout, stderr)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#221]
Currently there are `assert_exit_code()` and `assert_output_has()`. It would be nice to have unified method to test external process behaviour.

**Comment by ilyash** [comment]
Should be easily solvable with `=~` pattern matching

**Comment by ilyash-b** [comment]
Already works with `=~`
```
$(ls).processes[0] =~ {"exit_code": 0, "outputs": {1: /json/}}
```
