### ISSUE TITLE
Ignoring exit signal too verbose

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#257]
When ignoring an exit signal (when we kill a process on purpose) we have to do something like:

```
try {
	$($cmd)
} catch(e:ProcessFail) {
	# We are expecting the process to be killed
	guard e.process.exit_signal
	null
}
```

For exit signals we can do  ` ok: 10 ` for an exit code of 10.
Would be nice to have something like `ok_signal:SIGNALS.TERM` to allow a one liner on exit signal checking cases.

**Comment by ilyash-b** [comment]
In `dev`
