### ISSUE TITLE
XML->NGS 

### ISSUE THREAD

**Issue by zglozman** [ngs-lang/ngs#265]
What would be cool is to take an XML file, basically parse the schema, and create an NGS Object which could then serialize to JSON !!!!!! But it would also scaffold the xml the same way that msft tools do. 

In general, the direction of thinking is to take a schema and create an ngs language model for it. so you could easily work with data in any format. 
so #184 issue could be solved by parsing the data format document somehow and autogenerating an object model.

**Comment by ilyash-b** [comment]
> parse the schema

You mean guess?

> create an NGS Object which could then serialize to JSON 

The parsing/guessing the schema step was in order to parse "1" as a number and not as a string for example in this step?

> ngs language model for it

Currently NGS has no schema concept. It needs to be designed and implemented: #108 - Design and implement schema

> so #184 issue could be solved by parsing the data format 

Don't they have readily available schemas?

**Comment by ilyash** [comment]
Reopen if/when real life use cases appear
