### ISSUE TITLE
Prepare instructions/script for installing NGS in Cloud9

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#266]
WIP:

        sudo yum install cmake3
        sudo ln -s /usr/bin/cmake3 /usr/bin/cmake # check how to do without link
        sudo yum install pandoc # broken version -> pandoc: Unknown reader: markdown+hard_line_breaks
        make build

**Comment by ilyash-b** [comment]
Cloud9 now supports Ubuntu. If instructions will work for Ubuntu 18.04, that will be good enough.

**Comment by ilyash-b** [comment]
@organom , can you please check/confirm that installations instructions work well on Ubuntu 18.04?

**Comment by organom** [comment]
I would say that the installation steps should be:
-- to install
./install-linux.sh
make install

-- to build
make build

I'll confirm if they work ok and post here later on

**Comment by organom** [comment]
Instructions I gave above work perfectly in Ubuntu 18.04 LTS.  Tested on a locally installed VM

**Comment by ilyash-b** [comment]
Amazon Linux is now supported in `dev` branch. Closing.
