### ISSUE TITLE
Jupyter support

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#272]
# Requirements
* Ability to run NGS scripts
* (Later:) Appropriate support of `Table` output (check `%runsto`)

# Nice to have
* `debug()` integration
* `status()` integration

# Components

## NGS connector

* Receives commands on stdin, one JSON line at a time (split by `\n`).
* Evaluates the given expression
* Serializes the result
* Sends back (as one JSON line)
  * result
  * error
  * all newly-defined (were not present at startup) global variables.

## IPython extension

* `%` implementation
* `%%` implementation
* Sends expression to NGS connector
* Receives result
* Forwards the result to IPython
* Allows passing Python variables to NGS

# Protocol

* IPython -> NGS connector: `{"vars": {...}, "expr": ...}`.
* NGS connector: `{"result": ..., "output": ..., "error": ..., "vars": {...}}`

## `.result`

The field `.result` will not be present if there was an error

## `.output`

Array of arrays.
Example: `[[0, "blah"], [0, "xyz"], ["exc", "Invalid Argument"]]`

* First element of inner array: output channel. Either file descriptor (typically 0) or one of: `log`, `warn`, `error`, `exc`.
* Second element of inner array: text

## `.error`

The field `.error` will not be present if there was no error

* `.msg` - short error message
* `.text` - array of strings to show
* `.pos` - position of the error: [line, col] or `null`

## `.warn`

* `.text` - array of strings to show

# Protocol v2

NGS connector sends one event per line: `{"type": ...}`

* `{"type": "output", "channel": INT_OR_STR, "text": ...}`
  * channel string values: `log`, `warn`, `err`, `exc` 
* `{"type": "status", "text": ...}`
* `{"type": "progress", value: [current_item, total_items]}`
* `{"type": "result", "value": ...}`
* `{"type": "var", "name": ..., "value": ...}`
* `{ "type": "table", "columns_names":  [...], "rows": [  [...],  [...], ... ] }`
* `{"type": "error", "text_lines": [...], "class": ...}`
* `{"type": "finish"}`

**Comment by ilyash-b** [comment]
I wonder whether some ID is needed to synchronize requests and responses

**Comment by ilyash-b** [comment]
Summarizing: the feature is usable now.

**Comment by organom** [comment]
@ilyash can I close this, its available and documented in https://github.com/ngs-lang/ngs-ipython-extension

**Comment by ilyash-b** [comment]
Yep. I'll close since I'm here already :)
