### ISSUE TITLE
Duration type

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#298]

**Comment by antonio-pedro99** [comment]
could elaborate more on this?

**Comment by ilyash-b** [comment]
A data type for expressing difference between two points in time (`Time` objects)

**Comment by ilyash-b** [comment]
Maybe related to what's called `Duration` in other languages, needs checking

**Comment by antonio-pedro99** [comment]
something like this https://api.flutter.dev/flutter/dart-core/Duration-class.html ?

**Comment by ilyash-b** [comment]
> something like this https://api.flutter.dev/flutter/dart-core/Duration-class.html ?

Looks about right. To gather more ideas please also take a look at

* https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html
* https://learn.microsoft.com/en-us/dotnet/api/system.timespan.duration?view=net-6.0
* https://api.rubyonrails.org/classes/ActiveSupport/Duration.html

(and preferably other places too)

Since it might be a bigger task, I recommend preparing a design first (list of types and methods). Then we review the design. Then you can implement it.

**Comment by ilyash-b** [comment]
Already done
