### ISSUE TITLE
Consider syntax for literal multimethod

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#305]

**Comment by ilyash-b** [comment]
Currently can be written as `[1,2,"aa"].map(block _ { F f(x:Int) x+1; F f(x:Str) x+"!"; f })`

**Comment by ilyash-b** [comment]
Literal multimethod should probably cause the method lookup top to bottom, similar to `catch`.

**Comment by ilyash** [comment]
Have to see more use cases before doing this.

**Comment by ilyash** [comment]
Currently the following would be a good approximation to literal syntax: `{F f() 1; F f(x) 2; f}()`. Evaluates to the `f` multimethod. Does not pollute the namespace.
