### ISSUE TITLE
Make debug() more useable at least in main file

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#308]
Use case: one file script.

```
F my_debug(x:Str) debug("ensure-profiles", x)
...
my_debug("blah 1")
...
my_debug("blah 2")
```

There should be a simple way to select the main script file instead of the above plus `DEBUG=ensure-profiles`.

**Comment by ilyash** [comment]
Already done. `debug(msg)` is turned on with `DEBUG=default` environment variable (as opposed to stdlib and other predefined debugs, which are turned on with `DEBUG=*` or `DEBUG=facility_name`)
