### ISSUE TITLE
Consider syntax for Pred(x)(y)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#312]

**Comment by ilyash-b** [comment]
Or maybe a method name? Something like `y.check(x)`? Or maybe `x.Bool(y)`?

**Comment by ilyash-b** [comment]
Probably `~?` because it's similar to matching

**Comment by ilyash-b** [comment]
If `!` will be introduced as `not`, `!~?` would look pretty strange

**Comment by ilyash-b** [comment]
`y.test(x)` maybe

**Comment by ilyash-b** [comment]
... except the `test` method is used for testing

**Comment by ilyash** [comment]
Already done: `y =~ x`
