### ISSUE TITLE
Consider adding assert(x, Type)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#313]

**Comment by ilyash-b** [comment]
Thought: `assert(x, predicate)`, where `predicate` is used after conversion with `Pred`, like in `filter()`, etc.

**Comment by ilyash-b** [comment]
Also: think about `test` library and the `assert_`* functions there

**Comment by ilyash** [comment]
Already done: `assert(value, pattern, ...)` (in `dev` branch)

Asserts for tests is related topic but should be it's own issue.
