### ISSUE TITLE
Command line flag for "load file"

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#320]
Desired functionality: load a file to be able to use methods defined there and then execute code given on command line. Something like `ngs -l myfile.ngs -e 'myfync(7)'`.

**Comment by ilyash-b** [comment]
`-r` for `require`

**Comment by ilyash** [comment]
Nope.
`ngs -e "require('myfile.ngs'); ...."`
.. unless there will be frequent real use cases to make something shorter.
