### ISSUE TITLE
Consider adding before() and after() methods

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#333]
Somewhat common pattern `s.split(blah)[0]` could be more readable with `s.before(blah)`

**Comment by ilyash-b** [comment]
Thought:
`s[Before(blah)]`, where `Before` is a subtype of `Range`

**Comment by ilyash-b** [comment]
Probably: before_first, before_last, after_first, after_last

**Comment by ilyash** [comment]
`before()` and `after()` might be used to signify that exactly one occurrence is expected.

**Comment by ilyash** [comment]
Sounds good in general, will wait for more real life use cases before implementing.

* `before()`, `after()` - exactly one occurrence of the separator is expected.
* `before_first()`, `after_first()`
* `before_last()`, `after_last()`
