### ISSUE TITLE
Consider adding ensure(Num, Range) method

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#334]
Example `max(len(events) - start_limit, 0)` would become `(len(events) - start_limit).ensure(0..null)`

**Comment by ilyash-b** [comment]
Thoughts (not necessarily the syntax):

* `mynum.ensure(X<100)`
* `myarr.ensure(len(X) <= 10)` or `myarra.ensure(len, X<=10)`
* `mystr.ensure(len, 50, pad_with='-')` (how to specify left/right padding?)
* `mystr.adjust(len, 50, pad_with='-')` (how to specify left/right padding?)
* `len(mystr) = 50` (how to specify padding character and left/right?)

**Comment by ilyash-b** [comment]
It seems that for numbers, the consistent thing would probably be to `mynum.limit(Range)`

**Comment by ilyash** [comment]
Not enough real life use cases
