### ISSUE TITLE
Building on MSYS2

### ISSUE THREAD

**Issue by nu8** [ngs-lang/ngs#359]
I found this strange command:

https://github.com/ngs-lang/ngs/blob/5b94fd6f06370247c9ef198fd3337dedbf6f381b/CMakeLists.txt#L33-L38

What is `leg`? I have never heard of that, and its causing breaking on my system
(Windows MSYS2):

~~~
[ 14%] Generating syntax.include
/bin/sh: leg: command not found
[ 21%] Generating syntax.auto.h
[ 28%] Generating pcre_constants.include
Scanning dependencies of target ngs
make[3]: Leaving directory '/d/Git/gulf/ngs/ngs/build'
make[3]: Entering directory '/d/Git/gulf/ngs/ngs/build'
[ 35%] Building C object CMakeFiles/ngs.dir/ngs.c.obj
In file included from D:/Git/gulf/ngs/ngs/ngs.c:13:
D:/Git/gulf/ngs/ngs/compile.h:50:2: error: unknown type name 'ast_node'
   50 |  ast_node *ns[COMPILE_MAX_FUNC_DEPTH];
      |  ^~~~~~~~
~~~

**Comment by ilyash** [comment]
Hi!

Sorry for the delay! Crazy week.

`leg` is a parser from https://www.piumarta.com/software/peg/

Additional information: note that NGS was never tested on Windows MSYS2, currently supported platforms are Linux and MacOS. Given that, I would like to help you to get it running.

**Comment by ilyash** [comment]
Given the [What is the difference between Cygwin and MinGW?](https://stackoverflow.com/questions/771756/what-is-the-difference-between-cygwin-and-mingw) StackOverflow comparison, it looks like if you want to run NGS on Windows, Cygwin is the more practical approach.

**Comment by ilyash** [comment]
Not completely sure if possible. Can you use the package at https://www.archlinux.org/packages/community/x86_64/peg/ ?

**Comment by nu8** [comment]
Now I get this:

~~~
ngs/obj.c:2:10: fatal error: execinfo.h: No such file or directory
    2 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
~~~

**Comment by ilyash** [comment]
I'll look into this. Two alternatives I see at the moment:

1. Use #ifdef etc to disable the associated functionality in NGS
1. Install `execinfo.h` - currently, not sure if possible and how to do it, need to dig

**Comment by ilyash** [comment]
I would like to reproduce the error on my side. Can you please provide me with the steps you have taken? Among other things, how you solved the missing `leg`? I want our setup to be as similar as possible. Also, it would be a great start for documentation / scripting of installation on MSYS2.

**Comment by ilyash** [comment]
Meanwhile I've made dependency on `execinfo.h` optional instead of required.

Please try the `dev` branch.

**Comment by nu8** [comment]
Now I get this:

~~~
/bin/sh: xxd: command not found
~~~

and MSYS2 doesnt provide that, like Leg. Honestly it seems like you rely to heavily on these specialized tools to do the build. It would be better if you could just write some Perl scripts or something, then you could ditch these special tools as build requirement.

**Comment by ilyash** [comment]
For now, does this help - https://github.com/msys2/MINGW-packages/issues/3518?

I need to think about the tools approach. I considered `xxd` to be pretty basic thing to have in a system and the plan was to support Linux and MacOS, where this is not a problem.

**Comment by nu8** [comment]
I am not installing Vim just to get `xxd`, especially when it is so easy to
replace using standard tools. For example, here is a replacement using PHP:

~~~
<?php
$s_file = $argv[1];
$s_out = strtr($s_file, '/.', '__');
$s_get = file_get_contents($s_file);
$a_char = unpack('C*', $s_get);
$s_char = implode(',', $a_char);
$n_char = count($a_char);
echo <<<eof
unsigned char ${s_out}[] = {
   ${s_char}
};
unsigned int ${s_out}_len = ${n_char};
eof;
~~~

could easily be adapted to Perl or whatever language works best.

**Comment by ilyash** [comment]
In general, it would be a good thing to get rid of `xxd` build time dependency. It will take me a while to figure this out (how? if script it, which language is the "right" one?). What do you think about temporary workaround in which the build process would except an environment variable with the command to use instead of `xxd -i`?

**Comment by nu8** [comment]
This can be solved different ways. For example, here is a POSIX shell script:

~~~sh
#!/bin/sh
s_file=$1
s_out=$(tr /. __ <<eof
$s_file
eof
)
n_char=$(wc -c < "$s_file")
s_char=$(od -A n -t d1 "$s_file" | sed 's/[[:digit:]] /&,/g')
printf 'unsigned char %s[] = {
   %s
};
unsigned int %s_len = %s;
' "$s_out" "$s_char" "$s_out" "$n_char"
~~~

with this, you wouldnt even have to worry about any extra packages. As long as
user is on a POSIX system (which MSYS2 is one of) then its done.

**Comment by ilyash** [comment]
Looks good. I'll try to switch to this. Thanks!

**Comment by ilyash** [comment]
Done. Try the `dev` branch.

**Comment by nu8** [comment]
Now I get this:

~~~
D:/Desktop/ngs/vm.c:7:10: fatal error: sys/poll.h: No such file or directory
    7 | #include <sys/poll.h>
      |          ^~~~~~~~~~~~
~~~

that file is not available from native Windows packages, so it will need to be
`#ifdef` away, or replaced with something similar if building for Windows.

**Comment by ilyash** [comment]
Sounds good. I'll do it. It will be `#ifdef` and higher levels will deal with differences.

**Comment by ilyash** [comment]
Done. Try the `dev` branch.

FYI:

On my system:
```
$ ngs -p FEATURES.poll
true
```
On your system, you should see `false`.

**Comment by nu8** [comment]
Another one. Again not available with native Windows:

~~~
D:/Desktop/ngs/vm.c:34:10: fatal error: sys/wait.h: No such file or directory
   34 | #include <sys/wait.h>
      |          ^~~~~~~~~~~~
~~~

**Comment by ilyash** [comment]
I estimate there will be quite an effort involved.

1. Can you please provide the details of your setup so I could iterate quickly? In particular, how you got the peg/leg package. Please take into account that I'm not typically using Windows and never heard of MSYS before this issue. (I got MSYS installed and took a quick look at the package manager).
2. What is your expected use case for NGS? If it's interactive shell for example - it's not there yet and therefore the effort is not warranted.

**Comment by nu8** [comment]
I am looking for alternatives to PowerShell, script use would be good, but interactive use is also important. So if interactive use is not ready then perhaps we can end the discussion.

If you still want to know my build process, I can provide it.

**Comment by ilyash-b** [comment]
Thanks for explaining the use case.

Interactive use is not ready yet, as per readme:

> I have designed and implemented a programming language with typical Ops tasks in mind. See the use cases below. The next big planned part is the interactive shell.

If it's interesting, I have outlined the ideas for the UI at https://github.com/ngs-lang/ngs/wiki/UI-Design

As to

> If you still want to know my build process, I can provide it.

Yes, please! There is a chance of me getting there sometime in the future, probably after the UI.

**Comment by nu8** [comment]
ok - my build process is in the recycle bin of my home computer - I will post it after work

**Comment by nu8** [comment]
So first I install all packages. I had first tried with Windows native Cmake,
which didnt work, so several of the `mingw` packages are not actually required.
However so many are listed, that I dont want to go through to see what is
actually needed.

I will say as an aside, the NGS is one of the heaviest programs I have ever
compiled, and I have been compiling for many years. I have built native Windows
versions of cURL, Git, even FFmpeg and NGS beats them all in terms in package
requirements. I would against strongly advise to look at all the currnet NGS
requirements and see if any can be removed. That being said, I dont prefer to
use the MSYS2 environment day to day, I only use it for compiling. So I wrote
my own MSYS2 package manager:

https://github.com/nu8/cove/tree/master/msys2-pkg

I will put the package list at the end, because it is large. Again all not
needed, but most are. Next, here is my Peg build script. Its in PowerShell, you
can convert to Bash or whatever as needed:

~~~
Push-Location
Set-Location peg-0.1.18
$env:PATH = 'C:\msys2\mingw64\bin;C:\msys2\usr\bin'
mingw32-make
Copy-Item leg.exe C:\msys2\mingw64\bin
Pop-Location
~~~

and here is NGS build script (currently broken as discussed):

~~~
Push-Location
$env:PATH = 'C:\msys2\mingw64\bin;C:\msys2\usr\bin;C:\git\libexec\git-core'
git clone git://github.com/ngs-lang/ngs
Set-Location ngs
git checkout dev
make build
Pop-Location
~~~

Package list:

~~~
bash
brotli
cmake
coreutils
findutils
gawk
gcc-libs
gmp
grep
heimdal-libs
jsoncpp
libarchive
libbz2
libcrypt
libcurl
libexpat
libiconv
libidn2
libintl
liblz4
liblzma
libnghttp2
libopenssl
libpcre
libpsl
libreadline
librhash
libsqlite
libssh2
libunistring
libuv
libzstd
make
mingw-w64-x86_64-binutils
mingw-w64-x86_64-brotli
mingw-w64-x86_64-bzip2
mingw-w64-x86_64-crt
mingw-w64-x86_64-curl
mingw-w64-x86_64-dlfcn
mingw-w64-x86_64-expat
mingw-w64-x86_64-gc
mingw-w64-x86_64-gcc
mingw-w64-x86_64-gcc-libs
mingw-w64-x86_64-gettext
mingw-w64-x86_64-gmp
mingw-w64-x86_64-headers
mingw-w64-x86_64-json-c
mingw-w64-x86_64-jsoncpp
mingw-w64-x86_64-libarchive
mingw-w64-x86_64-libffi
mingw-w64-x86_64-libiconv
mingw-w64-x86_64-libidn2
mingw-w64-x86_64-libpsl
mingw-w64-x86_64-libssh2
mingw-w64-x86_64-libunistring
mingw-w64-x86_64-libuv
mingw-w64-x86_64-libwinpthread
mingw-w64-x86_64-lz4
mingw-w64-x86_64-make
mingw-w64-x86_64-nghttp2
mingw-w64-x86_64-pcre
mingw-w64-x86_64-pkg-config
mingw-w64-x86_64-rhash
mingw-w64-x86_64-windows-default-manifest
mingw-w64-x86_64-winpthreads
mingw-w64-x86_64-xz
mingw-w64-x86_64-zlib
mingw-w64-x86_64-zstd
mpfr
msys2-runtime
ncurses
pkg-config
sed
zlib
~~~

**Comment by ilyash** [comment]
Thanks!

>  all the current NGS requirements and see if any can be removed.

I don't take dependencies easily. On the other hand, can't rip parser (peg) for example out of the language. Maybe I could bundle it. Following that direction: It seems that the focus of other programming languages is to provide overall good user experience for the installation on supported platforms. Ruby for example has installer - https://rubyinstaller.org/ . When NGS starts supporting Windows, I guess the focus should also be on good UX as opposed to eliminating dependencies.

**Comment by nu8** [comment]
If NGS ever gets to a point where you can build a native Windows version, then simply distributing a prebuilt executable would go a long way. Most people don't want to build themselves, especially Windows users and eat C.

With other languages you can just `go build` or similar and everything just works. So if a Windows build is ever possible that would be my recommendation (to host a build). Even a once a year build would be better than nothing.

**Comment by ilyash-b** [comment]
> distributing a prebuilt executable

Makes the most sense, yes.

Thanks!

> If NGS ever gets to a point where you can build a native Windows version

I guess I'll comment on this issue to let you know.
