### ISSUE TITLE
GPL-3.0 is deprecated

### ISSUE THREAD

**Issue by chenrui333** [ngs-lang/ngs#384]
👋  GPL-3.0 is deprecated in favor of `GPL-3.0-or-later` or `GPL-3.0-only`. See more details in [SPDX list](https://spdx.org/licenses/).

--

relates to https://github.com/Homebrew/homebrew-core/pull/68148

**Comment by ilyash-b** [comment]
Thanks! We will take a look.

**Comment by organom** [comment]
Accepted and closed in brew, closing issue
