### ISSUE TITLE
Consider adding fetch() shortcut

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#388]
Common use case is to start the code with `fetch().` when using `ngs -p`, `ngs -pl`, etc. It would be nice to have some shorter way to have `fetch()` there.

Maybe: if code starts with `.` - replace it with `fetch().`

`curl http://localhost:5555/fhir/Patient | ngs -pl 'fetch().entry.resource.id' # fetch patients’ ids (first 20)` would be `curl http://localhost:5555/fhir/Patient | ngs -pl '.entry.resource.id' # fetch patients’ ids (first 20)`

**Comment by ilyash** [comment]
The `.somehing` to `fetch().something` transformation is problematic because `[something]` can not be transformed to `fetch()[something]` - `[something]` is a valid syntax.

**Comment by ilyash** [comment]
Already done. `ngs -e '_.myfield'`

If/when global variable `_` is used but it is not defined, its value is set to `fetch()`
