### ISSUE TITLE
Consider adding uniqueness check function

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#396]
... or some other facility to provide the functionality

Current uniqueness check looks like `my_arr.Stats().values().all(1)`

**Comment by ilyash-b** [comment]
... and just in case: `duplicates = my_arr.Stats().filterv(X>1).keys()`

**Comment by ilyash** [comment]
Thought: my_arr.window(2).all({ A[0] == A[1] })   # Add window(Eachable1, Fun)

**Comment by ilyash-b** [comment]
Not enough real world use cases at the moment. `duplicates(...).not()` can be used for now.
