### ISSUE TITLE
Exposing CLI sub-commands

### ISSUE THREAD

**Issue by ilyash** [ngs-lang/ngs#406]
It's common to have CLI utilities where the first argument is a sub-command. Example: `git commit`.

While the "straightforward" way in NGS would be to have `F main("commit", ...) ...` and so on (note: pattern matching in parameters is not implemented yet), the other good way would be to have a namespace with functions for each sub-command: `ns { ... F commit(...) ... }` which would be more friendly if the file is `require()`d and used from another ngs script.

TODO: Design how the language/stdlib understands that the namespace exposes this functions as CLI sub-commands. Somewhat similar to how `main` is handled (but in this case convention can not help, the functions will have arbitrary names).

**Comment by ilyash** [comment]
Subtype of Namespace maybe?

**Comment by ilyash** [comment]
An attribute of Namespace? (That will require a syntax to conveniently set attributes of namespaces)

**Comment by ilyash-b** [comment]
Already implemented
