### ISSUE TITLE
Updating fields which are optional should be more convenient

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#416]
Common pattern is to perform an action on a field but that field is not neccessrily present.

Example:
```
if 'resolved_lookup' in ret {
  ret.resolved_lookup = ret.resolved_lookup.values
}
```

First thing that comes to mind is: `ret.update('resolved_lookup', X.values)` but that precludes the callback accessing other fields (in case where ret is in Arr and the callback is called for each element of that array). Maybe pass both the subject and the whole object? It's also not obvious to the reader how `update()` handles missing fields (should ignore).

**Comment by ilyash** [comment]
To consider: fuse with pattern matching. Something like:
`ret =~ {'resolved_lookup': Arr ??? Update(X.values)}` where `???` is some new syntax/operator maybe.

**Comment by ilyash** [comment]
The `???` syntax is now implemented as `->`.

**Comment by ilyash** [comment]
Thought: `transform(x, {'resolved_lookup': Hash -> X.values})`

**Comment by ilyash** [comment]
Thought:
```
doc %STATUS - experimental
F replace(e:Eachable2, key_pattern, mapper:Fun) {
	# This implementation is probably O(1) for any key_pattern that
	# can be used as key in a Hash such as Int, Str, etc.
	# to_replace = e.keys().filter(key_pattern) would be O(n)
	to_replace = collector {
		e =~ {key_pattern -> collect: Any}
	}
	to_replace.each(F(k) {
		e[k] = mapper(e[k])
	})
	e
}
```

**Comment by ilyash** [comment]
Since `tr` facility is in a relatively good shape now (in `dev` branch), we can now do `ret .= tr({"resolved_lookup": Hash -> X.values})`

That should be enough for now. Reopen if the operation is observed to be more frequent (and hence current solution too verbose).
