### ISSUE TITLE
Add Not to stdlib

### ISSUE THREAD

**Issue by ilyash** [ngs-lang/ngs#417]
As part of [pattern matching facility](https://github.com/ngs-lang/ngs/wiki/UPM-Design), there should be `Not(some_pattern)` which
* Return `true` if `some_pattern` did not match and
* Return `false` if `some_pattern` did match

Please remember
* Create pull requests against the `dev` branch
* Provide some `doc` documentation as for other types
* Other types to look at to get the feeling: `AnyOf`, `AllOf`
* stdlib is at `lib/stdlib.ngs`
* Since `stdlib` is embedded in the binary, remember to rebuild (run `make` in the build directory) as part of the development cycle

**Comment by Ix1x0x3** [comment]
Sorry, what? 
![image](https://user-images.githubusercontent.com/96854760/151690702-06348940-c6a3-46b0-81a0-af99fac9491e.png)

**Comment by ilyash-b** [comment]
In `dev`
