### ISSUE TITLE
Create install.sh 

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#422]
Script minimal requirements:

Minimal requirements are `curl`, `grep`, `head`, `cut` and `tar`.
- For macos `brew` is required.
- For linux `apt` is required.

Script is : 
```
NGS_TMP_FOLDER=ngs_$RANDOM
​
mkdir $NGS_TMP_FOLDER
cd $NGS_TMP_FOLDER
​
curl $(curl -s https://api.github.com/repos/ngs-lang/ngs/releases | grep tarball_url | head -n 1 | cut -d '"' -f 4) -L -o ngs.tgz
tar -xvzf ngs.tgz --strip-components=1
​
OS=`uname`
if [ "$OS" = "Darwin" ]; then
  echo "Running on Mac"
  ./install-mac.sh 
else
  echo "Running on Linux"
  ./install-linux.sh
fi
​
cd ..
rm -rf $NGS_TMP_FOLDER
```

Run script as : 

```
curl -L https://.../install.sh | bash -s --
```

Add to script points from @ilyash 
```
trap EXIT
#!/usr/bin/env bash
mktemp
echo "If the installation fails, please open issue at …"
```

**Comment by organom** [comment]
Would be nice to have a link like  install.ngs-lang.org   that would point directly to the file, this way we could do `curl -L https://install.ngs-lang.org | bash -s --`

**Comment by ilyash** [comment]
I know it's not the same but it looks cleaner - https://github.com/trogdoro/xiki/blob/master/install_xsh

We need to check if we can do something like that

**Comment by ilyash** [comment]
In `dev`. Can not be fully tested until merged to master.

@organom , can you please take a look why Docker fails to build? I don't know if it is related to changes that I have made for this issue. The suspect is merging `./install-linux.sh` and `./install-mac.sh` into `install.sh`. I thought that I fixed all the references but maybe I missed something?

**Comment by ilyash** [comment]
Docker build - I'll open another issue
