### ISSUE TITLE
Add exponentiation operator

### ISSUE THREAD

**Issue by 2x-1** [ngs-lang/ngs#424]

**Comment by ilyash-b** [comment]
NGS language design principle is to have syntax only for the most frequent things.

How about `pow(base, exponent)` method?

**Comment by ilyash** [comment]
Never imagined it's such a mess - https://linux.die.net/man/3/pow - the errors.

While I'm on it, out of curiosity, what's the use case? I'm using NGS for years and can't remember single time I needed `pow()` (except recently to do some comparison on HN to contrived example in another language).

**Comment by ilyash** [comment]
Added to `dev` branch.

https://github.com/ngs-lang/ngs/commit/b3929c4b8d8fcf8ca0e613caf585e341aac3b0f7

Feel free to re-open if you have any questions.
