### ISSUE TITLE
Implement default limit in pmap threads

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#431]
Would make sense to implement some kind of limit to the number of threads when none is defined

Feedback from meetup:
`Limit by number of virtual cores.` - Daniel Eiband
`Usually most tools default to the number or cores/cpus available` - Fulvio Scapin

**Comment by ilyash** [comment]
I expect that given the nature of tasks, the threads will mostly be in i/o wait state (`ssh`ing somewhere or doing API calls with `curl`). In that case the limit should be `virtual_cores * 1024` or alike.

On the other hand we don't want to choke the computer if the threads happen to be CPU intensive. In which case the limit should  be lower.

Not sure how to balance the above.

**Comment by organom** [comment]
I would say `virtual_cores * 1` that's generally what other tools do and what devs expect from a default behavior. If the dev wants more or faster, then it should specify manually.   
Better to get it slower than to risk clogging the PC. What do you think?

**Comment by ilyash-b** [comment]
Pseudo scientific experiment on 2.5 GHz Dual-Core Intel Core i7:

```
$ ngs -e 'for par in [1,2,4,8,10,100,1000,2000,4000] { echo("+ $par"); F f(x) { a=0; for(i;1000000/par) {a+=1; a+=2} }; time({par.pmap(f)}).echo() }'+ 1
5467855
+ 2
2891444
+ 4
2773392
+ 8
3020003
+ 10
3068061
+ 100
3137871
+ 1000
3409933
+ 2000
4048332
+ 4000
5440365
```

**Comment by ilyash-b** [comment]
.. and with horrible hack to eliminate method lookup:

```
$ ngs -e 'plus=(+).Arr()[2]; for par in [1,2,4,8,10,100,1000,2000,4000] { echo("+ $par"); F f(x) { a=0; for(i;1000000/par) {a .= plus(1); a .= plus(2)} }; time({par.pmap(f)}).echo() }'

+ 1
2354322
+ 2
1223898
+ 4
1149247
+ 8
1324282
+ 10
1262442
+ 100
1240900
+ 1000
1693636
+ 2000
2312580
+ 4000
3702381

```

**Comment by ilyash** [comment]
On Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz running Linux 5.4.0-72-generic #80-Ubuntu SMP

```
$ ngs -e 'for par in [1,2,4,8,10,100,1000,2000,4000,8000] { echo("+ $par"); F f(x) { a=0; for(i;1000000/par) {a+=1; a+=2} }; time({par.pmap(f)}).echo() }'

+ 1
10193673
+ 2
5126209
+ 4
2799725
+ 8
2464486
+ 10
2526393
+ 100
2712065
+ 1000
3198655
+ 2000
3873581
+ 4000
5036758
+ 8000
6969294
```

**Comment by ilyash** [comment]
https://stackoverflow.com/questions/4586405/how-to-get-the-number-of-cpus-in-linux-using-c

**Comment by ilyash** [comment]
In `dev`
