### ISSUE TITLE
Consider Has pattern

### ISSUE THREAD

**Issue by ilyash** [ngs-lang/ngs#457]
`[1, 2, 3] =~ Has(2)`

The name `Has` is semantically fine but NGS also has `has()`. One letter case difference might be confusing.

Note that for `Hash`es it's a solved problem:

`my_hash =~ {KEY_PATTERN: VALUE_PATTERN}` (use `Any` instead of either key of pattern if you only need to check presence of the other one)

**Comment by ilyash-b** [comment]
There is already `Present` and `Absent` types. They should be used. TODO: Implement pattern matching for the mentioned types.

**Comment by ilyash-b** [comment]
In `dev`
