### ISSUE TITLE
my_arr.my_field = v should take Eachable1

### ISSUE THREAD

**Issue by ilyash** [ngs-lang/ngs#463]
Currently `my_arr.my_field = v` will assign `v` to all `my_field` fields in each of the elements of `my_arr`. This is a design bug. It's not symmetric with `my_arr.my_field` which returns an `Arr`.

TODO: `v` should be `Eachable1` and `my_field` of `my_arr` elements should be set to corresponding values of `v`.

**Comment by ilyash-b** [comment]
In `dev`
