### ISSUE TITLE
Brew package

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#47]

**Comment by ilyash-b** [comment]
should include vim highlighting

**Comment by organom** [comment]
@ilyash whats missing on this one?

**Comment by ilyash-b** [comment]
Brew package is maintained by 3rd party, closing.

https://formulae.brew.sh/formula/ngs

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ngs.rb
