### ISSUE TITLE
Add ensure(Int, NumRange)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#488]
Make sure that returned Int is in the given Range.

If the provided Int is out of Range, return the closest end of the range, otherwise return the original Int.

Test cases that come to mind:
* `ensure(5, 1..10) == 5`
* `ensure(1, 3..10) == 3`
* `ensure(20, 3...10) == 10`
* `ensure(20, 3..null) == 20` -- range without end
* Not sure what to do about Ranges that don't include the end `ensure(20, 3..10) == ?`

**Comment by antonio-pedro99** [comment]
What really this function does? 
Ensuring if a given integer is within a Range. Right?

**Comment by ilyash-b** [comment]
> What really this function does? Ensuring if a given integer is within a Range. Right?

Yep. Sometimes you have a number and it must be withing a given range or you put it in the range. That's exactly what ensure() should do.

**Comment by antonio-pedro99** [comment]
Got it.

**Comment by antonio-pedro99** [comment]
I am on it

**Comment by antonio-pedro99** [comment]
@ilyash-b Please mention where this is supposed to be implemented.

**Comment by ilyash-b** [comment]
I noticed there is no `section "Int"` in stdlib. Let's add

```
section "Int" {
  ...
}
```

Just about `section "Real"` - https://github.com/ngs-lang/ngs/blob/5ab2577a249c459aaf8a44a318d6aabc0f5a6b88/lib/stdlib.ngs#L1751

`F ensure(...)` would go inside the section then.

**Comment by ilyash-b** [comment]
Ooops. My mistake. `Range` is not defined there. Let's just add the code inside `section "Range"` in stdlib.

**Comment by ilyash-b** [comment]
Clarification, the `ensure()` should be specifically for `NumRange` subtype because it doesn't make sense for `PredRange`. I'll update the title of the issue.

**Comment by antonio-pedro99** [comment]
Sounds nice.

**Comment by ilyash-b** [comment]
In `dev`
