### ISSUE TITLE
MacOS man not working

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#492]
I believe its not added to the install.sh script

**Comment by ilyash** [comment]
https://github.com/ngs-lang/ngs/blob/44a9d3fe897e7e52856ce00515aa713aeeb6d6bd/CMakeLists.txt#L94
https://github.com/ngs-lang/ngs/blob/44a9d3fe897e7e52856ce00515aa713aeeb6d6bd/CMakeLists.txt#L106

Can't think of anything else

**Comment by organom** [comment]
in devf
