### ISSUE TITLE
TL;DR page creation

### ISSUE THREAD

**Issue by EmilySeville7cfg** [ngs-lang/ngs#495]
Please create tldr page for your shell. ;)

**Comment by ilyash** [comment]
As temporary "solution", extreme TL;DR is as follows:

* NGS is a modern programming language for DevOps.
* UI is [designed](https://github.com/ngs-lang/ngs/wiki/UI-Design) to some degree but not implemented yet.
* Short tutorial - https://ngs-lang.org/doc/latest/man/ngstut.1.html
* Why NGS was created - https://ngs-lang.org/doc/latest/man/ngswhy.1.html

Which content would you expect on such a page?

**Comment by EmilySeville7cfg** [comment]
I expect short tutorial content in tldr. Is is the most suitable from other suggestions at my glance.

**Comment by ilyash** [comment]
If https://ngs-lang.org/doc/latest/man/ngstut.1.html completely satisfies then we can close this issue.

If not, let me know. I would actually encourage you to imagine that this conversation did not happen and I did not give any information and think from that point what the perfect TL;DR page would have, not what from the above is a good approximation.

**Comment by EmilySeville7cfg** [comment]
I've created simple [tldr](https://github.com/tldr-pages/tldr/pull/7435) for ngs.

**Comment by ilyash** [comment]
Thanks!
