### ISSUE TITLE
`make tests` doesn't run all the tests

### ISSUE THREAD

**Issue by organom** [ngs-lang/ngs#504]
Currently `make tests` only runs the `ctests`.

The command should be improved with running also the ngs main tests (`./tests.ngs`) and any other relevant test that may be executed somewhere else

**Comment by ilyash** [comment]
Invalid.
There is no `tests.ngs` there is `test.ngs` and it's being called from `ctests`:

```
add_test(all bash -c "${CMAKE_CURRENT_BINARY_DIR}/ngs ${CMAKE_CURRENT_SOURCE_DIR}/test.ngs")
```
