### ISSUE TITLE
Add yum-based Linux distros builds (GH actions)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#507]
* Amazon Linux 2
* CentOS 7, 8
* Fedora 34, 35

**Comment by organom** [comment]
Implemented with:
- AmazonLinux 2  - default gcc and default clang
- Fedora 34 & 35 - default gcc and default clang
- CentOS 8 - default gcc (8.5) and default clang  + gcc 9 and 10

- CentOS 7 - compilation not working with gcc 9, 10 or 11 - complains about not defined MAP_ANONYMOUS  --  @ilyash can you please look into this? https://github.com/ngs-lang/ngs/runs/4743489825?check_suite_focus=true

**Comment by ilyash** [comment]
Adding `-D_BSD_SOURCE` should help. 
File: `/CMakeLists.txt`
Line: `add_definitions(-D_XOPEN_SOURCE=700 -D_DARWIN_C_SOURCE=1 -D_DEFAULT_SOURCE=1)`
Place: just before `)`, don't forget space before the new definition

Source (man mmap):

> Certain flags constants are defined only if suitable feature test macros are defined (possibly by default): _DEFAULT_SOURCE with glibc 2.19 or later; or _BSD_SOURCE or _SVID_SOURCE in glibc 2.19 and earlier.

**Comment by ilyash-b** [comment]
In `dev`
