### ISSUE TITLE
Clarification about new types' methods and data members

### ISSUE THREAD

**Issue by rdje** [ngs-lang/ngs#545]
Reading NGS version 0.2.13 manual it wasn't crystal clear whether or not one could add type specific methods and data members.

It turned out new types don't have methods per se and also their data/variable members are not declared.
Type data/variable members spring into existence when assigned a value.

It would help if those aspects could be clarified in order to remove any ambiguities especially when coming from languages implementing classes.

**Comment by ilyash-b** [comment]
@rdje , https://github.com/ngs-lang/ngs/commit/ef518167c4119a9f44e867376673b852a3edf08a - what do you think?

OK - close the issue
Not OK - comment here and/or create pull request with improvements

**Comment by rdje** [comment]
Ilya,

I am ok with the clarification.

-Richard
