### ISSUE TITLE
[UPM] Requirements: disabling backtracking and variable assignment in RE

### ISSUE THREAD

**Issue by rdje** [ngs-lang/ngs#546]
- There is a bullet about disabling backtracking after matching a subpattern

           I think PCRE, Perl5 or Raku will provide ways to do that, syntaxically I mean

- There is a bullet for capturing and assigning to variables

        When it comes to assigning to variables inside Regexes, we can achieve this in Perl5 using (?{ code })

**Comment by ilyash-b** [comment]
The bullet points are about "universal" pattern matching for all data structures. You can add the information above to the wiki page. Closing. Feel free to re-open if needed.
