### ISSUE TITLE
[UPM] Syntax

### ISSUE THREAD

**Issue by rdje** [ngs-lang/ngs#548]
- Under the TODO bullets of the Syntax Preliminary Thoughts

      Why not simply using  Hash["a"]["b"][Int] or Hash{"a"}{"b"}:Int

     We could even try to get rid of the double-quotes inside the curly brackets by automatically stringifying what's double-quoted.

**Comment by ilyash-b** [comment]
Thanks! Added to the wiki page to consider later. Feel free to describe there how it would work. We can also think about this later, when active development comes to that part.
