### ISSUE TITLE
[FR] Trailing closure syntax

### ISSUE THREAD

**Issue by rdje** [ngs-lang/ngs#552]
NGS supports Closures.

But it doesn't seem to have support for the so called ***trailing closure syntax***.

It is when calling a function and the last argument of that function is a closure, one may pop it out of the function's  parentheses and have it dangling outside of it after the closing parenthesis of the function, like this

> 1.  funcname(..., _closure_)  <=>  funcname(...)  _closure_
> 2.  funcname(_closure_)      <=>  funcname()  _closure_   <=>  funcname _closure_

When dangling outside of the function's argument list, the _closure_ has the following form

> `{ code }`

Ruby, Groovy, Kotlin, Swift and Raku support this _syntactic sugar_ feature.

- Is there any even remote plan to support trailing closure syntax ?
- Will you be even interested to have NGS support the trailing closure syntax ?

**Comment by ilyash-b** [comment]
> But it doesn't seem to have support for the so called trailing closure syntax.

## The Problem

I am thinking about this from time to time and don't know how to solve syntactic ambiguity that this would case:

`if CONDITION YES_BODY NO_BODY`, for example: `if 1 my_func() { A + 1 }`. Is `{A + 1}` the NO_BODY here or last argument to `my_func()`.

## Closest Thing

NGS has a way to supply arguments after the `my_func()` parenthesis using `with` or `do` syntax:

```
test("my test") with { ... }
my_func(1,2) do { ... }
```


* `with` and `do` are repeatable so you can `my_func() do { ... } do { ...}`
* `with` and `do` can be followed by anything, not just closure: `my_func() with 1 with 2 with { ... }`

## Thoughts

* Having both `with` and `do` for the same functionality is very likely a mistake
* Repeatable `with` and `do` have roughly zero observed real use cases.
* The ability to use `with` and `do` not only with closures also have roughly zero observed real use cases.
* Trailing closure syntax does make the syntax a bit cleaner.
* I find myself using `with` and `do` less and less over time.
* As the time passes by I'm having more doubts that the additional syntax is worth it.

**Comment by rdje** [comment]
Ok then, it seems you already had this trailing closure syntax feature in mind for some time now.

So feel free to close my FR then.

**Comment by ilyash-b** [comment]
Let's break our heads on that if/when there is more demand.
