### ISSUE TITLE
tests not passing while in dev branch[make tests]

### ISSUE THREAD

**Issue by antonio-pedro99** [ngs-lang/ngs#588]
I forked the repo and installed it while I was in master branch.
`make tests` was working
`make build` was working 

I checked out to dev branch and tried `make` tests but I am getting this error[tests are failing]

![Screenshot from 2022-10-02 21-02-40](https://user-images.githubusercontent.com/42675180/193462411-4fd0d012-2177-4776-a530-8afd442c84f0.png)

**Comment by ilyash-b** [comment]
Currently on MacOS. Unable to reproduce.

1. Try `rm -rf build`, build, and test again
2. If it does not solve: Take a look at last 20 or so lines in `build/Testing/Temporary/LastTest.log`. Paste here.

**Comment by ilyash-b** [comment]
In general it's recommended to paste the text to GH issues. It's searchable as opposed to screenshots.

**Comment by ilyash-b** [comment]
Another direction is to try to see the difference between GitHub of the project and your environment. GHA also to tests and they pass. Comparing and finding differences in setup might help.

**Comment by antonio-pedro99** [comment]
I have fixed it by reinstalling.
1. ./install.sh
2. make tests
3. make build

Now it is working fine.
