### ISSUE TITLE
A single # on a line should count as a comment

### ISSUE THREAD

**Issue by MinmoTech** [ngs-lang/ngs#610]
As also reported on discord currently a single `#` on a line causes a compilation error.
It works when putting a whitespace after it: `# `

Ideally this single `#` on a line would also just count as a comment as is documented here:
https://ngs-lang.org/doc/latest/man/ngslang.1.html

**Comment by ilyash-b** [comment]
The fix is in the `dev` branch. If you are on `dev`, we should close it now. If you are using the `master` branch, we should close it after the release.
