### ISSUE TITLE
NGS Docker image outdated

### ISSUE THREAD

**Issue by MinmoTech** [ngs-lang/ngs#636]
With the currently available version (`ngslang/ngs:v0.2.12`) I get this issue because of the outdated base image when trying to update:

```
+docker *failed* | E: The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.
+docker *failed* | E: The repository 'http://deb.debian.org/debian stretch-updates Release' does no longer have a Release file.
```

**Comment by ilyash-b** [comment]
Fixed in `dev` branch.

Docker build should be periodically tested. Added https://github.com/ngs-lang/ngs/issues/637

**Comment by organom** [comment]
Same as https://github.com/ngs-lang/ngs/issues/640
