### ISSUE TITLE
Add ensure(Eachable1, Present)

### ISSUE THREAD

**Issue by ilyash-b** [ngs-lang/ngs#646]

**Comment by antonio-pedro99** [comment]
Hi @ilyash-b, could you provide more info on this?

**Comment by ilyash-b** [comment]
Hi @antonio-pedro99!

In general, `ensure(original, pattern)` returns a value which would match the pattern. The operation to make the original conform to the pattern should be minimal and obvious.

```
my_arr = [1,2,3]
my_arr =~ Has(1)  # true
my_arr =~ Has(4)  # false
ensure(my_arr, Has(4))  # [1,2,3,4]

```

**Comment by antonio-pedro99** [comment]
I did not understood this
```bash
ensure(my_arr, Has(4))
```
Returning 1, 2, 3 + the element that is not present.

**Comment by ilyash-b** [comment]
Not sure I understand your comment. I'll try to explain slightly different and see if it works.

`ensure(x, pattern)` should return a value that would match the `pattern`. In other words, `ensure(x, pattern) =~ pattern` should succeed.

* If `x =~ pattern` when `ensure()` is called, it just needs to return `x`
* Otherwise, `ensure()` should minimally transform (a copy of) `x` so that returned value matches the `pattern`

In the example of `ensure(my_arr, Has(4))`, where `4` is not in `my_arr` that minimal transformation would be to return a new value with all the elements of `my_arr` with the item `4` appended.

**Comment by ilyash-b** [comment]
In `dev`
