### ISSUE TITLE
Documentation: Comparison with PowerShell / NuShell

### ISSUE THREAD

**Issue by Malix-off** [ngs-lang/ngs#670]
It would be very nice to know your opinion towards Powershell, and also more particularly [NuShell](https://www.nushell.sh/), as I find these two to be the closest of the purpose of NGS in the first place

**Comment by Malix-off** [comment]
See https://www.reddit.com/u/ilyash/s/F9q41Q1OWW

**Comment by ilyash-b** [comment]
Also see https://github.com/ngs-lang/ngs?tab=readme-ov-file#have-you-heard-of-project-x-how-it-compares-to-ngs

If that's what you expect, please close the issue. If not, what's missing?

**Comment by Malix-off** [comment]
Indeed, I missed

"Nu Shell"
 https://github.com/ngs-lang/ngs#:~:text=similar%20to%20Shell%2B%2B.-,Nu%20Shell,-%2D%20compared%20on%202020

Thanks !
