### ISSUE TITLE
AWS Lambda Custom Runtime for NGS

### ISSUE THREAD

**Issue by zglozman** [ngs-lang/ngs#88]

**Comment by ilyash-b** [comment]
Tutorial: https://aws.amazon.com/blogs/compute/scripting-languages-for-aws-lambda-running-php-ruby-and-go/

**Comment by ilyash-b** [comment]
Design is at https://github.com/ngs-lang/ngs/wiki/Running-as-AWS-Lambda-Design

**Comment by ilyash** [comment]
TODO: Support NGS as one of the languages for AWS SAM

**Comment by ilyash** [comment]
Done. Documentation is in `dev` branch. The solution is at https://github.com/ngs-lang/ngs-aws-lambda
